### PR TITLE
feat: added Filters

### PR DESCRIPTION
**Pull request by AnjaliDeshwani**
**Added filters on Product Page**
- Sort by Price, Rating and category, PriceRange

**Preview available at -**  https://deploy-preview-2--winsome-books-store.netlify.app/

### CODE REVIEW

**Review by znjs — APPROVED** [review]
Clean code
good naming conventions used
good folder structure

**Comment by znjs** [comment]
Suggestion: can apply price range filter on `onMouseUp` instead of `onChange`, can use `onChange` to update the value on UI

**Review by manismk — APPROVED** [review]
Clean UI
Good naming convention and code is easy to understand

**Comment by AnjaliDeshwani** [comment]
> Suggestion: can apply price range filter on `onMouseUp` instead of `onChange`, can use `onChange` to update the value on UI

I have updated it now. Thanks @znjs for pointing it out, I was not knowing about it.

**Pull request merged**
